language: shell

os:
  - linux
  - osx

addons:
  homebrew:
    packages:
      - coreutils
      - jq

before_install:
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
  - . $HOME/.asdf/asdf.sh

before_script:
  - asdf plugin add troubleshoot-live ./

script:
  - asdf list all troubleshoot-live
  - asdf install troubleshoot-live latest
  - asdf global troubleshoot-live latest
  - troubleshoot-live help
