language: shell

os:
  - linux
  - osx

addons:
  homebrew:
    packages:
      - coreutils
      - go

before_install:
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
  - . $HOME/.asdf/asdf.sh

install:
  - asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
  - asdf install golang latest
  - asdf global golang latest
  - unset GOROOT
  - go version
  - go env GOPATH
  - asdf plugin-add jq https://github.com/AZMCode/asdf-jq.git
  - asdf install jq latest
  - asdf global jq latest
  - curl -s https://api.github.com/repos/mhrabovcin/troubleshoot-live/releases | jq -r '.[].tag_name' | sed 's/^v//' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tr ' ' '\n' | sort -u -V | tr '\n' ' '

before_script:
  - asdf plugin add troubleshoot-live ./
  - asdf list all troubleshoot-live

script:
  - asdf install troubleshoot-live latest
  - asdf global troubleshoot-live latest
  - troubleshoot-live help
