language: go

go:
  - "1.20.x"

env:
  - GO111MODULE=on

before_script:
  - git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
  - . $HOME/.asdf/asdf.sh
  - asdf plugin add troubleshoot-live ./

script:
  - asdf install troubleshoot-live latest
  - asdf global troubleshoot-live latest
  - troubleshoot-live --help
